### ISSUE TITLE
Feature request for class decorator

### ISSUE THREAD

**Issue by jmvtrinidad** [variotry/knockout-decorator#2]
It is possible to create a class decorator that will convert all property and accessors to observable?

**Comment by variotry** [comment]
I have added `@track` class decorator.
The decorator converts all properties and accessors to observable.

Points to consider.
1. Have to initialize properties at place of declaration or in constructor to be recognized as observable.
   (set `null` is OK also)
2. Have to set array value for array properties to be recognized as oservable array.
   If you first set null to a array property, the property will recognize as KnockoutObservable&lt;T[]>,
   not KnockoutObservableArray&lt;T>.
3. Accessors will be converted to pure computed.
   If you want to use non pure computed, pass argument { pureComputed:true } to `@track` or attach `@computed` decorator to accessors.
4. If you want to prevent properties or accessors from converting to observable, attach `@ignore` decorator to them.

**Comment by jmvtrinidad** [comment]
Thanks for this. 
Also I think you should improve this page ranking on Google to show this repo on keywords `knockout typescript decorator` or similar keywords.

**Comment by variotry** [comment]
Thanks.
I will give it a try.
